/*
 * routing.c - see routing.h. No device header, no driver include: this file
 * only counts resources and compares route_t values against each other, it
 * never touches a register.
 *
 * Check order inside routing_add() (documented here, not just implied by
 * the code, because tests/host/test_routing.c relies on it to isolate one
 * rule at a time when several would fail on the same call): pin
 * reachability, core exclusivity, SCCP, DMA, DAC outputs, UREF, RAM, then
 * the N+1 sink gate. SCCP is checked before DMA on purpose: a route that
 * plays a table costs one of each per routing.h's model, so a call that
 * would exceed both at once reports SCCP_LIMIT, not DMA_LIMIT - the only
 * way to observe the SCCP rule at all, since nothing in the model can ever
 * cost more SCCP than DMA.
 */
#include "routing.h"

#define ROUTE_MAX_ROUTES 24u

/* generated by tools/gen_route_pins.py from tools/pins128.py (the
 * dsPIC33AK512MPS512, DS70005591D Table 11) - do not hand-edit, re-run the
 * script instead. One bit per PINSEL that reaches a package pin on that
 * core; PINSEL 7 (UREF) is not in this table, see ROUTE_PINSEL_UREF in
 * routing.h. Only the EV74H48A's device is covered - N+1 permits exactly
 * one route, fixed to this device's pin (docs/IMPLEMENTATION-PLAN.md P11.3);
 * a second table for the EV17P63A Nano (tools/pins64.py, MPS506) is for
 * whoever gives routing.c a board parameter later. */
static const uint8_t route_pin_mask[ROUTE_ADC_CORES] = {
    0x1Fu, /* core 1: PINSEL 0, 1, 2, 3, 4 */
    0x3Fu, /* core 2: PINSEL 0, 1, 2, 3, 4, 5 */
    0x3Fu, /* core 3: PINSEL 0, 1, 2, 3, 4, 5 */
    0x3Fu, /* core 4: PINSEL 0, 1, 2, 3, 4, 5 */
    0x1Fu, /* core 5: PINSEL 0, 1, 2, 3, 4 */
};

static route_t  route_table[ROUTE_MAX_ROUTES];
static uint32_t route_count = 0u;

bool route_pin_reachable(uint8_t core, uint8_t pinsel)
{
    if (core < 1u || core > ROUTE_ADC_CORES) { return false; }
    if (pinsel == ROUTE_PINSEL_UREF) { return true; }
    if (pinsel > 7u) { return false; } /* PINSEL is wider than the pins this
                                        * table models; nothing routing_add()
                                        * builds today passes more than 7 */
    return (route_pin_mask[core - 1u] & (1u << pinsel)) != 0u;
}

void routing_clear(void)
{
    route_count = 0u;
}

/* ---- aggregates over route_table[0..route_count), the state BEFORE the
 * candidate route is added ---- */

static bool core_in_use(uint8_t core)
{
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].core == core) { return true; }
    }
    return false;
}

static uint32_t count_adc_consuming(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src != ROUTE_SRC_RAM_TABLE) { n++; }
    }
    return n;
}

static uint32_t count_table_dacs(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].table_samples > 0u) { n++; }
    }
    return n;
}

static uint32_t count_dac_pin(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src == ROUTE_SRC_DAC_PIN) { n++; }
    }
    return n;
}

static uint32_t count_dac_int(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src == ROUTE_SRC_DAC_INT) { n++; }
    }
    return n;
}

static uint32_t ram_used_bytes(void)
{
    uint32_t bytes = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        const route_t *x = &route_table[i];
        if (x->src != ROUTE_SRC_RAM_TABLE) { bytes += ROUTE_CHANNEL_BYTES; }
        bytes += x->table_samples * ROUTE_SAMPLE_BYTES;
    }
    return bytes;
}

route_err_t routing_add(const route_t *r)
{
    if (r->core != ROUTE_CORE_NONE) {
        if (!route_pin_reachable(r->core, r->pinsel)) {
            return ROUTE_ERR_PIN_UNREACHABLE;
        }
        if (core_in_use(r->core)) {
            return ROUTE_ERR_CORE_IN_USE;
        }
    }

    const bool     r_is_adc      = (r->src != ROUTE_SRC_RAM_TABLE);
    const bool     r_has_table   = (r->table_samples > 0u);
    const uint32_t adc_after     = count_adc_consuming() + (r_is_adc ? 1u : 0u);
    const uint32_t table_after   = count_table_dacs() + (r_has_table ? 1u : 0u);

    const uint32_t sccp_after = (adc_after > 0u ? 1u : 0u) + table_after;
    if (sccp_after > ROUTE_SCCP_COUNT) {
        return ROUTE_ERR_SCCP_LIMIT;
    }

    const uint32_t dma_after = adc_after + table_after;
    if (dma_after > ROUTE_DMA_CHANNELS) {
        return ROUTE_ERR_DMA_LIMIT;
    }

    if (r->src == ROUTE_SRC_DAC_PIN
        && count_dac_pin() + 1u > ROUTE_DAC_OUTPUTS) {
        return ROUTE_ERR_DAC_OUTPUTS;
    }

    if (r->src == ROUTE_SRC_DAC_INT
        && count_dac_int() + 1u > ROUTE_UREF_COUNT) {
        return ROUTE_ERR_UREF_BUSY;
    }

    uint32_t ram_after = ram_used_bytes();
    if (r_is_adc) { ram_after += ROUTE_CHANNEL_BYTES; }
    ram_after += r->table_samples * ROUTE_SAMPLE_BYTES;
    if (ram_after > ROUTE_RAM_BUDGET_BYTES) {
        return ROUTE_ERR_RAM_BUDGET;
    }

    if (r->sink != ROUTE_SINK_STREAM) {
        return ROUTE_ERR_NOT_YET;
    }

    if (route_count >= ROUTE_MAX_ROUTES) {
        return ROUTE_ERR_TABLE_FULL;
    }
    route_table[route_count] = *r;
    route_count++;
    return ROUTE_OK;
}
