/*******************************************************************************
 * Copyright (C) 2026 Microchip Technology Inc. and its subsidiaries.
 *
 * Subject to your compliance with these terms, you may use Microchip software
 * and any derivatives exclusively with Microchip products. It is your
 * responsibility to comply with third party license terms applicable to your
 * use of third party software (including open source software) that may
 * accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE.
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 * ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 ******************************************************************************/

/*
 * routing.c - see routing.h. No device header, no driver include: this file
 * only counts resources, compares route_t values against each other and -
 * since P11.3 (27.09.2026) - asks acquisition.c to bring one path up. It
 * never touches a register itself. The only firmware it calls is
 * acquisition.h's acq_chain_setup_input() and acq_chain_restore(), which is
 * what keeps tests/host/test_routing.c buildable: the host test defines
 * those two as counting stubs and links this file alone.
 *
 * Check order inside routing_add() (documented here, not just implied by
 * the code, because tests/host/test_routing.c relies on it to isolate one
 * rule at a time when several would fail on the same call): pin
 * reachability, core exclusivity, SCCP, DMA, DAC outputs, UREF, RAM, then
 * the N+1 sink gate. SCCP is checked before DMA on purpose: a route that
 * plays a table costs one of each per routing.h's model, so a call that
 * would exceed both at once reports SCCP_LIMIT, not DMA_LIMIT - the only
 * way to observe the SCCP rule at all, since nothing in the model can ever
 * cost more SCCP than DMA.
 *
 * routing_visit() (P11.5, 27.09.2026), for the console command "route
 * list": stays exactly as print-free as the rest of this file - it hands
 * every field to the caller's route_visit_t (routing.h) instead of calling
 * console_puts()/put_kv() itself, the same visitor pattern port/regs.h uses
 * for a driver's register dump, so routing.c still links into
 * tests/host/test_routing.c without a console.
 */
#include <stddef.h>          /* NULL, routing_visit()'s v/s arguments (P11.5) */

#include "routing.h"
#include "acquisition.h"

#define ROUTE_MAX_ROUTES 24u

/* One bit per PINSEL that reaches a package pin on that core; the internal
 * channels (PINSEL 6/7 everywhere, 5/8 on core 5) are not in this table,
 * see route_int_mask[] below. Two
 * tables, one per device the firmware builds for, selected by the device
 * macro xc-dsc defines from -mcpu (the trace harness's fake xc.h defines
 * the same one per NAME.mcu): which PINSEL reaches a pin is a property of
 * the PACKAGE, so the device, not board.h's BOARD, is the right key - and
 * this file does not include board.h, so that a host gcc still compiles it.
 * The host build gets the MPS512's table, the one tests/host/test_routing.c
 * asserts against. */
/* generated by tools/gen_route_pins.py from tools/pins128.py and
 * tools/pins64.py - see that script for how; do not hand-edit without
 * re-running it. */
static const uint8_t route_pin_mask[ROUTE_ADC_CORES] = {
#if defined(__dsPIC33AK512MPS506__)
    /* dsPIC33AK512MPS506, 64 pins (tools/pins64.py) - the EV17P63A */
    0x1Fu, /* core 1: PINSEL 0, 1, 2, 3, 4 */
    0x1Fu, /* core 2: PINSEL 0, 1, 2, 3, 4 */
    0x27u, /* core 3: PINSEL 0, 1, 2, 5 */
    0x3Fu, /* core 4: PINSEL 0, 1, 2, 3, 4, 5 */
    0x1Fu, /* core 5: PINSEL 0, 1, 2, 3, 4 */
#else
    /* dsPIC33AK512MPS512, 128 pins (tools/pins128.py) - the EV74H48A,
     * and the host build (no device macro) */
    0x1Fu, /* core 1: PINSEL 0, 1, 2, 3, 4 */
    0x3Fu, /* core 2: PINSEL 0, 1, 2, 3, 4, 5 */
    0x3Fu, /* core 3: PINSEL 0, 1, 2, 3, 4, 5 */
    0x3Fu, /* core 4: PINSEL 0, 1, 2, 3, 4, 5 */
    0x1Fu, /* core 5: PINSEL 0, 1, 2, 3, 4 */
#endif
};

/* One bit per PINSEL that is an INTERNAL channel of that core - no package
 * pin, reachable on every package, so not in route_pin_mask[] and not
 * generated: read off the pack's ATDF by hand (P11.4, 27.09.2026;
 * dsPIC33AK-MP_DFP 1.4.260, dsPIC33AK512MPS512.atdf and ...MPS506.atdf, the
 * ADC module's per-instance <param>s, identical on both devices):
 *   every core   ADnAN6 "15/16*VDD Reference Input", ADnAN7 "Uref Input"
 *                (ROUTE_PINSEL_VREF/ROUTE_PINSEL_UREF, routing.h)
 *   core 5 only  AD5AN5 "Touch ADC Input", AD5AN8 "VDDCORE"
 * ADnAN9..15 carry no <param> on either device (the PINSEL value-group
 * AD_CH_CON1__PINSEL merely lists AD_AN0..15 as numbers), so they are
 * treated as reserved and refused. Before P11.4 "stream on <ksps> <core>
 * <pinsel>" accepted any PINSEL 0..15 unchecked; the GUI's "6 = internal
 * ref" hint (tools/adc_gui.py) is why 6 had to stay reachable. */
static const uint16_t route_int_mask[ROUTE_ADC_CORES] = {
    (1u << ROUTE_PINSEL_VREF) | (1u << ROUTE_PINSEL_UREF),               /* core 1 */
    (1u << ROUTE_PINSEL_VREF) | (1u << ROUTE_PINSEL_UREF),               /* core 2 */
    (1u << ROUTE_PINSEL_VREF) | (1u << ROUTE_PINSEL_UREF),               /* core 3 */
    (1u << ROUTE_PINSEL_VREF) | (1u << ROUTE_PINSEL_UREF),               /* core 4 */
    (1u << 5) | (1u << ROUTE_PINSEL_VREF) | (1u << ROUTE_PINSEL_UREF) | (1u << 8), /* core 5 */
};

static route_t  route_table[ROUTE_MAX_ROUTES];
static uint32_t route_count = 0u;

bool route_pin_reachable(uint8_t core, uint8_t pinsel)
{
    if (core < 1u || core > ROUTE_ADC_CORES) { return false; }
    if (pinsel > 15u) { return false; }             /* PINSEL is 4 bits wide */
    if ((route_int_mask[core - 1u] & (1u << pinsel)) != 0u) { return true; }
    if (pinsel > 7u) { return false; }              /* route_pin_mask[] is 8 bits */
    return (route_pin_mask[core - 1u] & (1u << pinsel)) != 0u;
}

void routing_clear(void)
{
    route_count = 0u;
}

/* ---- the signal generator's claim (SG.5, 29.09.2026) ----
 * Held apart from route_table: the generator is not a signal path into an
 * ADC, it outlives "stream on/off" (whose routing_clear() empties the
 * table), and exactly one can run. While it runs it counts in the
 * aggregates below like a route playing a table on its own pin - one DMA
 * channel, one SCCP, one DAC output, its table's RAM - and its DAC is
 * busy for any route that wants the same DAC (ROUTE_ERR_DAC_BUSY), in
 * both directions: routing_gen_check() refuses a DAC a route uses. */
static uint8_t  gen_dac = 0u;        /* 0 = no generator claimed       */
static uint32_t gen_n   = 0u;

/* ---- aggregates over route_table[0..route_count), the state BEFORE the
 * candidate route is added - the generator's claim included ---- */

static bool core_in_use(uint8_t core)
{
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].core == core) { return true; }
    }
    return false;
}

static uint32_t count_adc_consuming(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src != ROUTE_SRC_RAM_TABLE) { n++; }
    }
    return n;
}

static uint32_t count_table_dacs(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].table_samples > 0u) { n++; }
    }
    return n + ((gen_dac != 0u) ? 1u : 0u);
}

static uint32_t count_dac_pin(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src == ROUTE_SRC_DAC_PIN) { n++; }
    }
    return n + ((gen_dac != 0u) ? 1u : 0u);
}

static uint32_t count_dac_int(void)
{
    uint32_t n = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        if (route_table[i].src == ROUTE_SRC_DAC_INT) { n++; }
    }
    return n;
}

static uint32_t ram_used_bytes(void)
{
    uint32_t bytes = 0u;
    for (uint32_t i = 0; i < route_count; i++) {
        const route_t *x = &route_table[i];
        if (x->src != ROUTE_SRC_RAM_TABLE) { bytes += ROUTE_CHANNEL_BYTES; }
        bytes += x->table_samples * ROUTE_SAMPLE_BYTES;
    }
    return bytes + gen_n * ROUTE_SAMPLE_BYTES;
}

static bool uses_dac(const route_t *r, uint8_t dac)
{
    return ((r->src == ROUTE_SRC_DAC_PIN) || (r->src == ROUTE_SRC_DAC_INT)) && (r->dac == dac);
}

route_err_t routing_gen_check(uint8_t dac, uint32_t n)
{
    for (uint32_t i = 0; i < route_count; i++) {
        if (uses_dac(&route_table[i], dac)) { return ROUTE_ERR_DAC_BUSY; }
    }
    const uint32_t adc_n   = count_adc_consuming();
    const uint32_t table_n = count_table_dacs() + 1u;
    if ((adc_n > 0u ? 1u : 0u) + table_n > ROUTE_SCCP_COUNT) { return ROUTE_ERR_SCCP_LIMIT; }
    if (adc_n + table_n > ROUTE_DMA_CHANNELS)                { return ROUTE_ERR_DMA_LIMIT; }
    if (count_dac_pin() + 1u > ROUTE_DAC_OUTPUTS)            { return ROUTE_ERR_DAC_OUTPUTS; }
    if (ram_used_bytes() + n * ROUTE_SAMPLE_BYTES > ROUTE_RAM_BUDGET_BYTES) {
        return ROUTE_ERR_RAM_BUDGET;
    }
    return ROUTE_OK;
}

route_err_t routing_gen_claim(uint8_t dac, uint32_t n)
{
    const route_err_t e = routing_gen_check(dac, n);
    if (e != ROUTE_OK) { return e; }
    gen_dac = dac;
    gen_n   = n;
    return ROUTE_OK;
}

void routing_gen_release(void)
{
    gen_dac = 0u;
    gen_n   = 0u;
}

/* routing_add()'s rules without the recording - shared with routing_apply()
 * since P11.3, so that both check exactly the same things in exactly the
 * same order (the body is P11.1's routing_add() up to the store). */
static route_err_t route_check(const route_t *r)
{
    if (r->core != ROUTE_CORE_NONE) {
        if (!route_pin_reachable(r->core, r->pinsel)) {
            return ROUTE_ERR_PIN_UNREACHABLE;
        }
        if (core_in_use(r->core)) {
            return ROUTE_ERR_CORE_IN_USE;
        }
    }

    if ((gen_dac != 0u) && uses_dac(r, gen_dac)) {
        return ROUTE_ERR_DAC_BUSY;
    }

    const bool     r_is_adc      = (r->src != ROUTE_SRC_RAM_TABLE);
    const bool     r_has_table   = (r->table_samples > 0u);
    const uint32_t adc_after     = count_adc_consuming() + (r_is_adc ? 1u : 0u);
    const uint32_t table_after   = count_table_dacs() + (r_has_table ? 1u : 0u);

    const uint32_t sccp_after = (adc_after > 0u ? 1u : 0u) + table_after;
    if (sccp_after > ROUTE_SCCP_COUNT) {
        return ROUTE_ERR_SCCP_LIMIT;
    }

    const uint32_t dma_after = adc_after + table_after;
    if (dma_after > ROUTE_DMA_CHANNELS) {
        return ROUTE_ERR_DMA_LIMIT;
    }

    if (r->src == ROUTE_SRC_DAC_PIN
        && count_dac_pin() + 1u > ROUTE_DAC_OUTPUTS) {
        return ROUTE_ERR_DAC_OUTPUTS;
    }

    if (r->src == ROUTE_SRC_DAC_INT
        && count_dac_int() + 1u > ROUTE_UREF_COUNT) {
        return ROUTE_ERR_UREF_BUSY;
    }

    uint32_t ram_after = ram_used_bytes();
    if (r_is_adc) { ram_after += ROUTE_CHANNEL_BYTES; }
    ram_after += r->table_samples * ROUTE_SAMPLE_BYTES;
    if (ram_after > ROUTE_RAM_BUDGET_BYTES) {
        return ROUTE_ERR_RAM_BUDGET;
    }

    if (r->sink != ROUTE_SINK_STREAM) {
        return ROUTE_ERR_NOT_YET;
    }

    if (route_count >= ROUTE_MAX_ROUTES) {
        return ROUTE_ERR_TABLE_FULL;
    }
    return ROUTE_OK;
}

static void route_record(const route_t *r)
{
    route_table[route_count] = *r;
    route_count++;
}

route_err_t routing_add(const route_t *r)
{
    const route_err_t e = route_check(r);
    if (e != ROUTE_OK) { return e; }
    route_record(r);
    return ROUTE_OK;
}

/* Which route shapes acquisition.c can bring up today (P11.3), and what
 * each asks acq_chain_setup_input() for:
 *
 *   ROUTE_SRC_EXT              any core/pin (route_check() has already said
 *                              the core reaches it); the DAC is left alone
 *                              (test_dac = false) - "stream on <ksps> <core>
 *                              <pinsel> [<samc>]", CLAUDE.md "the DAC is
 *                              then left alone".
 *   ROUTE_SRC_DAC_PIN, dac 2   DAC2 started at mid-scale on its own pin
 *                              first (test_dac = true), the chain test's
 *                              and "stream on <ksps>"'s signal - the only
 *                              DAC dac.c drives on the pin route (dac2_*).
 *
 * Not yet (ROUTE_ERR_NOT_YET, before any driver call): a table to play
 * (table_samples > 0 - no signal generator DMA in N+1), ROUTE_SRC_DAC_INT
 * (the UREF route: UREFCON.INSEL is run_dactest()'s business in cli.c, not
 * acq_chain_setup()'s), ROUTE_SRC_RAM_TABLE (no ADC to set up), and any
 * DAC_PIN route naming another DAC than 2. */
static bool apply_shape_ok(const route_t *r, bool *test_dac)
{
    if (r->table_samples > 0u) { return false; }
    switch (r->src) {
    case ROUTE_SRC_EXT:
        *test_dac = false;
        return true;
    case ROUTE_SRC_DAC_PIN:
        *test_dac = true;
        return (r->dac == 2u);
    case ROUTE_SRC_DAC_INT:
    case ROUTE_SRC_RAM_TABLE:
    default:
        return false;
    }
}

/* The fixed order (docs/DESIGN-MULTICHANNEL.md 4.4: "all DMA channels off,
 * ADC cores off, set clock and trigger, cores on, DMA rebuilt from
 * scratch") is acq_chain_setup()'s body, called through acq_chain_setup_
 * input() with this route's core/pin/SAMC and DAC choice - the same body
 * chain_stream_on_input() has run since the chain test was written, so the
 * register sequence is the one the `stream_on` golden trace fixes
 * (tests/trace/scenarios/route_stream.c proves it line for line):
 *
 *   DMA off               capture_settle() (the channel down, the ADC
 *                         quiet), sccp1_stop() (the trigger off),
 *                         capture_set_half_len()
 *   cores off, clock,     capture_set_pll(5, 1) - PLL1 at 320 MHz, itself
 *   cores on              in the boot order: DMA down, core off, PLL
 *                         switched and read back, core on, DMA up again;
 *                         clock_trig_on() - CLKGEN13 for SCCP1;
 *                         clock_dac_select()/dac2_level_start() - CLKGEN7
 *                         and DAC2, if this route wants the signal
 *   cores on, DMA from    capture_select_core(core, pinsel, samc) - the
 *   scratch               full adc_init() + capture_init() on that core,
 *                         then adc_set_mode_single(SCCP1)/adc_set_irqsel(0)
 *   DMA off again         capture_settle() - the channel is left DOWN, and
 *                         the trigger stopped, for the caller's capture_
 *                         chain_start(): the rate is not the route's
 *
 * Splitting acq_chain_setup() into those steps here would only have moved
 * its body across a file boundary; the order is already the fixed one, so
 * the call is kept whole and the mapping is written down instead. */
route_err_t routing_apply(const route_t *r)
{
    const route_err_t e = route_check(r);
    if (e != ROUTE_OK) { return e; }

    bool test_dac = false;
    if (!apply_shape_ok(r, &test_dac)) { return ROUTE_ERR_NOT_YET; }

    if (!acq_chain_setup_input(r->core, r->pinsel, r->samc, test_dac)) {
        acq_chain_restore();                  /* as chain_stream_on_input() */
        return ROUTE_ERR_SETUP;
    }
    route_record(r);
    return ROUTE_OK;
}

/* route_src_t/route_sink_t as short, static strings for routing_visit()
 * (P11.5, 27.09.2026) - the ATDF-independent names routing.h's own enum
 * comments already use. */
static const char *route_src_name(route_src_t src)
{
    switch (src) {
    case ROUTE_SRC_EXT:       return "EXT";
    case ROUTE_SRC_DAC_INT:   return "DAC_INT";
    case ROUTE_SRC_DAC_PIN:   return "DAC_PIN";
    case ROUTE_SRC_RAM_TABLE: return "RAM_TABLE";
    default:                  return "?";
    }
}

static const char *route_sink_name(route_sink_t sink)
{
    switch (sink) {
    case ROUTE_SINK_RAM:     return "RAM";
    case ROUTE_SINK_CONSOLE: return "CONSOLE";
    case ROUTE_SINK_STREAM:  return "STREAM";
    default:                 return "?";
    }
}

void routing_visit(route_visit_t visit)
{
    if (route_count == 0u) {
        visit("route: none - no route active", 0u, NULL, ROUTE_VIS_LINE);
    } else {
        for (uint32_t i = 0; i < route_count; i++) {
            const route_t *r = &route_table[i];
            visit("route",  i,          NULL,                     ROUTE_VIS_NUM);
            visit("src",    0u,         route_src_name(r->src),   ROUTE_VIS_STR);
            visit("core",   r->core,    NULL,                     ROUTE_VIS_NUM);
            visit("pinsel", r->pinsel,  NULL,                     ROUTE_VIS_NUM);
            visit("dac",    r->dac,     NULL,                     ROUTE_VIS_NUM);
            visit("samc",   r->samc,    NULL,                     ROUTE_VIS_NUM);
            visit("sink",   0u,         route_sink_name(r->sink), ROUTE_VIS_STR);
        }
    }

    /* the resource table - the same counters route_check() charges a
     * candidate route against, read back rather than recomputed twice;
     * the generator's claim first, when there is one (SG.5) */
    if (gen_dac != 0u) {
        visit("generator_dac",     gen_dac,                 NULL, ROUTE_VIS_NUM);
        visit("generator_n",       gen_n,                   NULL, ROUTE_VIS_NUM);
    }
    const uint32_t adc_n   = count_adc_consuming();
    const uint32_t table_n = count_table_dacs();
    visit("dma_used",          adc_n + table_n,         NULL, ROUTE_VIS_NUM);
    visit("dma_total",         ROUTE_DMA_CHANNELS,       NULL, ROUTE_VIS_NUM);
    visit("sccp_used",         (adc_n > 0u ? 1u : 0u) + table_n, NULL, ROUTE_VIS_NUM);
    visit("sccp_total",        ROUTE_SCCP_COUNT,        NULL, ROUTE_VIS_NUM);
    visit("dac_outputs_used",  count_dac_pin(),         NULL, ROUTE_VIS_NUM);
    visit("dac_outputs_total", ROUTE_DAC_OUTPUTS,       NULL, ROUTE_VIS_NUM);
    visit("uref_used",         count_dac_int(),         NULL, ROUTE_VIS_NUM);
    visit("uref_total",        ROUTE_UREF_COUNT,        NULL, ROUTE_VIS_NUM);
    visit("ram_used",          ram_used_bytes(),        NULL, ROUTE_VIS_NUM);
    visit("ram_budget",        ROUTE_RAM_BUDGET_BYTES,  NULL, ROUTE_VIS_NUM);
}
