"""
gen_route_pins.py - derives, from tools/pins128.py, which ADC PINSEL values on
each core reach an external pin, for routing.c's pin-reachability check
(P11.1, docs/DESIGN-MULTICHANNEL.md section 4.4: "a pin on a core that
cannot reach it?").

tools/pins128.py's own header states the fact this script relies on: "AD3AN5"
in that table is the same name as PINSEL 5 on ADC core 3 in the firmware -
extracted from the family data sheet DS70005591D. So a token "AD<core>AN<n>"
(the positive input; "AD<core>ANN<n>" is the negative input of a
differential pair and is not a PINSEL value routing.c can select) in any pin
function string means: core <core>, PINSEL <n> reaches that package pin.
UREF (PINSEL 7) is not a package pin at all - board.h's own comment records
that it reaches every core (DS70005591D Table 16-2) - so it is not part of
this table and is handled as a constant in routing.c.

Run from the repository root: `python tools/gen_route_pins.py`. It only
reads tools/pins128.py (the dsPIC33AK512MPS512, the EV74H48A board ROUTE_STREAM
runs on - src/boards/board_cfg.h) and prints the C array `routing.c` embeds
as `route_pin_mask[]`, one bitmask per core (bit <n> set means PINSEL <n>
reaches a pin), so the derivation is reproducible and auditable instead of
hand-transcribed. It does not read pins64.py (the EV17P63A Nano/MPS506):
N+1 permits exactly one route, fixed to the EV74H48A pin, so a second table
is not yet needed - a note left in routing.c for whoever adds board-specific
reachability later.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def core_pinsel_map(pin_functions):
    """{core: {pinsel: pin}} from a PIN_FUNCTIONS table, positive inputs only."""
    cores = {}
    for pin, funcs in pin_functions.items():
        for token in funcs.split("/"):
            m = re.fullmatch(r"AD([0-9])AN([0-9])", token)
            if m:
                core = int(m.group(1))
                pinsel = int(m.group(2))
                cores.setdefault(core, {})[pinsel] = pin
    return cores


def render(cores, core_count):
    lines = []
    for core in range(1, core_count + 1):
        pinsels = cores.get(core, {})
        mask = 0
        for pinsel in pinsels:
            mask |= 1 << pinsel
        reached = ", ".join(str(p) for p in sorted(pinsels))
        lines.append(
            "    0x%02Xu, /* core %d: PINSEL %s */" % (mask, core, reached)
        )
    return "\n".join(lines)


def main():
    sys.path.insert(0, str(ROOT / "tools"))
    import pins128  # noqa: E402  (path set up above)

    cores = core_pinsel_map(pins128.PIN_FUNCTIONS)
    print("/* generated by tools/gen_route_pins.py from tools/pins128.py - see")
    print(" * that script for how; do not hand-edit without re-running it. */")
    print(render(cores, 5))


if __name__ == "__main__":
    main()
