"""
gen_route_pins.py - derives, from tools/pins128.py and tools/pins64.py, which
ADC PINSEL values on each core reach an external pin, for routing.c's
pin-reachability check (P11.1, docs/DESIGN-MULTICHANNEL.md section 4.4: "a
pin on a core that cannot reach it?").

tools/pins128.py's own header states the fact this script relies on: "AD3AN5"
in that table is the same name as PINSEL 5 on ADC core 3 in the firmware -
extracted from the family data sheet DS70005591D. So a token "AD<core>AN<n>"
(the positive input; "AD<core>ANN<n>" is the negative input of a
differential pair and is not a PINSEL value routing.c can select) in any pin
function string means: core <core>, PINSEL <n> reaches that package pin.
UREF (PINSEL 7) is not a package pin at all - board.h's own comment records
that it reaches every core (DS70005591D Table 16-2) - so it is not part of
this table and is handled as a constant in routing.c.

Run from the repository root: `python tools/gen_route_pins.py`. It reads
tools/pins128.py (the dsPIC33AK512MPS512, 128 pins - the EV74H48A board
ROUTE_STREAM runs on, src/boards/board_cfg.h) and tools/pins64.py (the
dsPIC33AK512MPS506, 64 pins - the EV17P63A Curiosity Nano) and prints the C
definition `routing.c` embeds as `route_pin_mask[]`: one bitmask per core
(bit <n> set means PINSEL <n> reaches a pin), the MPS506's table under the
device macro xc-dsc defines for that part (`__dsPIC33AK512MPS506__`; the
trace harness's fake header defines the same one for `nano.mcu`), the
MPS512's otherwise - which is also what the host build (tests/host/
test_routing.c, no device macro at all) gets. Keyed on the DEVICE, not on
board.h's BOARD: which PINSEL reaches a package pin is a property of the
package, and routing.c does not include board.h (it must stay compilable by
a host gcc). So the derivation is reproducible and auditable instead of
hand-transcribed. P11.1 read pins128.py only; P11.3 (27.09.2026) added
pins64.py when routing.c entered every build, the Nano's included.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def core_pinsel_map(pin_functions):
    """{core: {pinsel: pin}} from a PIN_FUNCTIONS table, positive inputs only."""
    cores = {}
    for pin, funcs in pin_functions.items():
        for token in funcs.split("/"):
            m = re.fullmatch(r"AD([0-9])AN([0-9])", token)
            if m:
                core = int(m.group(1))
                pinsel = int(m.group(2))
                cores.setdefault(core, {})[pinsel] = pin
    return cores


def render(cores, core_count):
    lines = []
    for core in range(1, core_count + 1):
        pinsels = cores.get(core, {})
        mask = 0
        for pinsel in pinsels:
            mask |= 1 << pinsel
        reached = ", ".join(str(p) for p in sorted(pinsels))
        lines.append(
            "    0x%02Xu, /* core %d: PINSEL %s */" % (mask, core, reached)
        )
    return "\n".join(lines)


def main():
    sys.path.insert(0, str(ROOT / "tools"))
    import pins128  # noqa: E402  (path set up above)
    import pins64   # noqa: E402

    print("/* generated by tools/gen_route_pins.py from tools/pins128.py and")
    print(" * tools/pins64.py - see that script for how; do not hand-edit without")
    print(" * re-running it. */")
    print("static const uint8_t route_pin_mask[ROUTE_ADC_CORES] = {")
    print("#if defined(__dsPIC33AK512MPS506__)")
    print("    /* dsPIC33AK512MPS506, 64 pins (tools/pins64.py) - the EV17P63A */")
    print(render(core_pinsel_map(pins64.PIN_FUNCTIONS), 5))
    print("#else")
    print("    /* dsPIC33AK512MPS512, 128 pins (tools/pins128.py) - the EV74H48A,")
    print("     * and the host build (no device macro) */")
    print(render(core_pinsel_map(pins128.PIN_FUNCTIONS), 5))
    print("#endif")
    print("};")


if __name__ == "__main__":
    main()
