@echo off
rem ---------------------------------------------------------------------
rem  Writes version.h in the repository root with the git revision of the
rem  working tree, so that the firmware's banner says which commit it is.
rem
rem  Runs before every build: MPLAB X pre-build step (both configurations),
rem  tools\build.bat, and tools\Makefile (through version.sh). Without git
rem  on the PATH it writes "unknown" and the build still succeeds.
rem  The file is rewritten only when its content changes, so an unchanged
rem  tree does not recompile main.c and cli.c on every build.
rem ---------------------------------------------------------------------
setlocal
set "ROOT=%~dp0.."
set "OUT=%ROOT%\version.h"
set "TMP=%ROOT%\version.h.tmp"
set REV=unknown
set BRANCH=unknown
set DIRTY=0
for /f "delims=" %%R in ('git -C "%ROOT%" rev-parse --short HEAD 2^>nul') do set "REV=%%R"
for /f "delims=" %%B in ('git -C "%ROOT%" rev-parse --abbrev-ref HEAD 2^>nul') do set "BRANCH=%%B"
for /f "delims=" %%S in ('git -C "%ROOT%" status --porcelain -uno 2^>nul') do set DIRTY=1
(
  echo /* generated by tools\version.bat - do not edit, not tracked */
  echo #define GIT_REV    "%REV%"
  echo #define GIT_BRANCH "%BRANCH%"
  echo #define GIT_DIRTY  %DIRTY%
) > "%TMP%"
if exist "%OUT%" (
  fc "%OUT%" "%TMP%" >nul 2>&1 && ( del "%TMP%" & goto :done )
)
move /y "%TMP%" "%OUT%" >nul
:done
echo version.h: %REV% %BRANCH% dirty=%DIRTY%
endlocal
