#!/bin/sh
# Same job as version.bat, for tools/Makefile under a POSIX shell (Git Bash,
# MSYS, Linux): write ../src/app/version.h (next to board.h, which includes
# it through __has_include) with the git revision, only when changed.
root=$(cd "$(dirname "$0")/.." && pwd)
out="$root/src/app/version.h"
rev=$(git -C "$root" rev-parse --short HEAD 2>/dev/null || echo unknown)
branch=$(git -C "$root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)
if [ -n "$(git -C "$root" status --porcelain -uno 2>/dev/null)" ]; then dirty=1; else dirty=0; fi
tmp="$out.tmp"
printf '/* generated by tools/version.sh - do not edit, not tracked */\n#define GIT_REV    "%s"\n#define GIT_BRANCH "%s"\n#define GIT_DIRTY  %s\n' "$rev" "$branch" "$dirty" > "$tmp"
if cmp -s "$tmp" "$out"; then rm -f "$tmp"; else mv -f "$tmp" "$out"; fi
echo "version.h: $rev $branch dirty=$dirty"
